/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Exchange API
 * OpenAPI spec version: 1.0
 */
import { calculatorInstance } from './api';
export interface ExchangeRequestV1 {
  amount: string;
  steps: string[];
}

export interface ExchangeResponseV1StepsItem {
  from: string;
  to: string;
  amountFrom: number;
  amountTo: number;
  rateFromTo: number;
}

export interface ExchangeResponseV1 {
  finalAmount?: number;
  steps?: ExchangeResponseV1StepsItem[];
}

export interface CurrencyRateV1 {
  code: string;
  name: string;
  nominal: number;
  rate: number;
}

export interface GetCurrencyRatesResponseV1 {
  [key: string]: CurrencyRateV1;
}

/**
 * @summary Получить курсы валют ЦБ на сегодня
 */
export const getCurrencyRates = () => {
  return calculatorInstance<GetCurrencyRatesResponseV1>({ url: `/api/v1/rates`, method: 'GET' });
};

/**
 * @summary Конвертация валюты по цепочке
 */
export const exchangeCurrency = (exchangeRequestV1: ExchangeRequestV1) => {
  return calculatorInstance<ExchangeResponseV1>({
    url: `/api/v1/exchange`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: exchangeRequestV1,
  });
};

export type GetCurrencyRatesResult = NonNullable<Awaited<ReturnType<typeof getCurrencyRates>>>;
export type ExchangeCurrencyResult = NonNullable<Awaited<ReturnType<typeof exchangeCurrency>>>;
